sudo: false
cache:
  directories:
    - bundler

language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"

script:
  - grunt test -v --stack -d

before_install:
  - npm install -g grunt-cli bower
  - gem install bundler
  - bundle install

before_script:
  - npm install
  - bower install

matrix:
  fast_finish: true

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc6e2b8f4026ae4c9896
    on_success: change
    on_failure: always
    on_start: false
